services:
  - type: web
    name: kobra-backend
    runtime: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: NODE_VERSION
        value: 20.18.0
    healthCheckPath: /health
